# Finding Compatibility With Car with ANN Classification

# Importing the Dataset 

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
le_y = LabelEncoder()
le_x = LabelEncoder()
from tensorflow.keras.utils import to_categorical

In [2]:
dataset = pd.read_csv('Car Compatibility.csv')
dataset

Buying Maintenance  Doors Persons Luggage_boot Safety Car Compatibility
0     vhigh       vhigh      2       2        small    low             unacc
1     vhigh       vhigh      2       2        small    med             unacc
2     vhigh       vhigh      2       2        small   high             unacc
3     vhigh       vhigh      2       2          med    low             unacc
4     vhigh       vhigh      2       2          med    med             unacc
...     ...         ...    ...     ...          ...    ...               ...
1723    low         low  5more    more          med    med              good
1724    low         low  5more    more          med   high             vgood
1725    low         low  5more    more          big    low             unacc
1726    low         low  5more    more          big    med              good
1727    low         low  5more    more          big   high             vgood

[1728 rows x 7 columns]

# Data Preprocessing

# Changing Index Starting as 1 and not 0

In [3]:
dataset.index = dataset.index + 1
dataset

Buying Maintenance  Doors Persons Luggage_boot Safety Car Compatibility
1     vhigh       vhigh      2       2        small    low             unacc
2     vhigh       vhigh      2       2        small    med             unacc
3     vhigh       vhigh      2       2        small   high             unacc
4     vhigh       vhigh      2       2          med    low             unacc
5     vhigh       vhigh      2       2          med    med             unacc
...     ...         ...    ...     ...          ...    ...               ...
1724    low         low  5more    more          med    med              good
1725    low         low  5more    more          med   high             vgood
1726    low         low  5more    more          big    low             unacc
1727    low         low  5more    more          big    med              good
1728    low         low  5more    more          big   high             vgood

[1728 rows x 7 columns]

# Changing Characters to Integers For compatibility with the model 

In [4]:
for i in dataset[dataset['Doors']=='2'].index.values:
    dataset['Doors'][i] = 2

In [5]:
for i in dataset[dataset['Doors']=='3'].index.values:
    dataset['Doors'][i] = 3

In [6]:
for i in dataset[dataset['Doors']=='4'].index.values:
    dataset['Doors'][i] = 4

In [7]:
for i in dataset[dataset['Doors']=='5more'].index.values:
    dataset['Doors'][i] = 5

In [8]:
for i in dataset[dataset['Persons']=='2'].index.values:
    dataset['Persons'][i] = 2

In [9]:
for i in dataset[dataset['Persons']=='4'].index.values:
    dataset['Persons'][i] = 4

In [10]:
for i in dataset[dataset['Persons']=='more'].index.values:
    dataset['Persons'][i] = 5

In [11]:
dataset

Buying Maintenance Doors Persons Luggage_boot Safety Car Compatibility
1     vhigh       vhigh     2       2        small    low             unacc
2     vhigh       vhigh     2       2        small    med             unacc
3     vhigh       vhigh     2       2        small   high             unacc
4     vhigh       vhigh     2       2          med    low             unacc
5     vhigh       vhigh     2       2          med    med             unacc
...     ...         ...   ...     ...          ...    ...               ...
1724    low         low     5       5          med    med              good
1725    low         low     5       5          med   high             vgood
1726    low         low     5       5          big    low             unacc
1727    low         low     5       5          big    med              good
1728    low         low     5       5          big   high             vgood

[1728 rows x 7 columns]

In [12]:
dataset['Buying'].value_counts()

high     432
vhigh    432
low      432
med      432
Name: Buying, dtype: int64

In [13]:
dataset['Maintenance'].value_counts()

high     432
vhigh    432
low      432
med      432
Name: Maintenance, dtype: int64

In [14]:
dataset['Luggage_boot'].value_counts()

big      576
small    576
med      576
Name: Luggage_boot, dtype: int64

In [15]:
dataset['Safety'].value_counts()

high    576
low     576
med     576
Name: Safety, dtype: int64

In [16]:
dataset['Car Compatibility'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: Car Compatibility, dtype: int64

In [18]:
dataset['Buying'].value_counts()
dataset['Maintenance'].value_counts()
dataset['Luggage_boot'].value_counts()
dataset['Safety'].value_counts()
dataset['Car Compatibility'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: Car Compatibility, dtype: int64

# Splitting the Dataset

In [19]:
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

# Label Encoding Rest of the Characters of Training Set for compatibility with the model 

In [20]:
y = le_y.fit_transform(y)
X[:, 0] = le_x.fit_transform(X[:, 0])
X[:, 1] = le_x.fit_transform(X[:, 1])
X[:, 4] = le_x.fit_transform(X[:, 4])
X[:, 5] = le_x.fit_transform(X[:, 5])

In [21]:
y

array([2, 2, 2, ..., 2, 1, 3])

In [22]:
X 

array([[3, 3, 2, 2, 2, 1],
       [3, 3, 2, 2, 2, 2],
       [3, 3, 2, 2, 2, 0],
       ...,
       [1, 1, 5, 5, 0, 1],
       [1, 1, 5, 5, 0, 2],
       [1, 1, 5, 5, 0, 0]], dtype=object)

In [23]:
Y = pd.get_dummies(y).values
Y = np.array(Y)
Y = Y.astype('int64')

In [24]:
Y

array([[0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       ...,
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1]], dtype=int64)

In [25]:
X

array([[3, 3, 2, 2, 2, 1],
       [3, 3, 2, 2, 2, 2],
       [3, 3, 2, 2, 2, 0],
       ...,
       [1, 1, 5, 5, 0, 1],
       [1, 1, 5, 5, 0, 2],
       [1, 1, 5, 5, 0, 0]], dtype=object)

In [26]:
print(X)

[[3 3 2 2 2 1]
 [3 3 2 2 2 2]
 [3 3 2 2 2 0]
 ...
 [1 1 5 5 0 1]
 [1 1 5 5 0 2]
 [1 1 5 5 0 0]]


# Feature Scaling

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

# Splitting Data into Training and Test

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# Applying Aritficial Neural Network

# ANN

In [29]:
ann = tf.keras.models.Sequential()

# Input Layer and 1st Hidden Layer

In [30]:
ann.add(tf.keras.layers.Dense(6, input_shape=(6,), activation='relu'))

# 2nd Hidden Layer

In [31]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

# Output Layer

In [33]:
ann.add(tf.keras.layers.Dense(4, activation='softmax'))

# Compiling ANN

In [34]:
ann.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Training ANN

In [35]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Train on 1382 samples
Epoch 1/100
1382/1382 [==============================] - 1s 692us/sample - loss: 1.3425 - accuracy: 0.5036
Epoch 2/100
1382/1382 [==============================] - 0s 96us/sample - loss: 1.2261 - accuracy: 0.6860
Epoch 3/100
1382/1382 [==============================] - 0s 100us/sample - loss: 1.0704 - accuracy: 0.7019
Epoch 4/100
1382/1382 [==============================] - 0s 79us/sample - loss: 0.9243 - accuracy: 0.7019
Epoch 5/100
1382/1382 [==============================] - 0s 83us/sample - loss: 0.8321 - accuracy: 0.7019
Epoch 6/100
1382/1382 [==============================] - 0s 72us/sample - loss: 0.7768 - accuracy: 0.7019
Epoch 7/100
1382/1382 [==============================] - 0s 84us/sample - loss: 0.7427 - accuracy: 0.7019
Epoch 8/100
1382/1382 [==============================] - 0s 107us/sample - loss: 0.7220 - accuracy: 0.7019
Epoch 9/100
1382/1382 [==============================] - 0s 77us/sample - loss: 0.7073 - accuracy: 0.7062
Epoch 10/100
1382/138

1382/1382 [==============================] - 0s 67us/sample - loss: 0.2137 - accuracy: 0.9211
Epoch 78/100
1382/1382 [==============================] - 0s 69us/sample - loss: 0.2115 - accuracy: 0.9182
Epoch 79/100
1382/1382 [==============================] - 0s 69us/sample - loss: 0.2102 - accuracy: 0.9211
Epoch 80/100
1382/1382 [==============================] - 0s 69us/sample - loss: 0.2071 - accuracy: 0.9182
Epoch 81/100
1382/1382 [==============================] - 0s 70us/sample - loss: 0.2045 - accuracy: 0.9197
Epoch 82/100
1382/1382 [==============================] - 0s 69us/sample - loss: 0.2017 - accuracy: 0.9255
Epoch 83/100
1382/1382 [==============================] - 0s 71us/sample - loss: 0.2008 - accuracy: 0.9233
Epoch 84/100
1382/1382 [==============================] - 0s 72us/sample - loss: 0.1985 - accuracy: 0.9226
Epoch 85/100
1382/1382 [==============================] - 0s 69us/sample - loss: 0.1984 - accuracy: 0.9233
Epoch 86/100
1382/1382 [==========================

# Label Encoded Buying:  
###               3:>>> vhigh
###               1:>>> low
###               0:>>>high
###               2:>>> med

# Doors:
### 2,3,4,5

# Persons:
## 2,4,5

#  Label Encoded Maintenance:  
###                        3:>>> vhigh
###                        1:>>> low
###                        0:>>>high
###                        2:>>>med

# Label Encoded Luggage_boot:  
###                        2:small
###                        1:med
###                        0:big

# Label Encoded Safety:
###                       1:>>>> low
###                       2:>>>> med
###                       0:>>>>high

# Evaluating Model with Classification Report and Confusion Matrix

In [36]:
y_pred = ann.predict(X_test)
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [37]:
from sklearn.metrics import classification_report , confusion_matrix
print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       0.79      0.89      0.83        79
           1       0.80      0.24      0.36        17
           2       0.97      0.97      0.97       240
           3       0.67      0.80      0.73        10

    accuracy                           0.91       346
   macro avg       0.81      0.72      0.72       346
weighted avg       0.91      0.91      0.90       346

[[ 70   1   7   1]
 [ 10   4   0   3]
 [  7   0 233   0]
 [  2   0   0   8]]
